name: Django CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run_pull:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 108.235.156.95
        username: hukum
        password: thinkagain@321
        port: 2222
        script: "cd test_deploy && git checkout main && git pull && exit"
