name: Django CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run_pull:
    runs-on: ubuntu-latest
    steps:
    - name: connect and pull
      run: ssh hukum@108.235.156.95 -p2222 thinkagain@123 "cd test_deploy && git checkout main && git pull && exit"
